import { readFileSync } from 'node:fs';
import { join } from 'node:path';

import { ScenarioSchema, DecisionAnalysisSchema } from '../domain/schema';
import { OUTPUT_SCHEMA, buildUserPrompt, validateRequest } from '../../supabase/functions/analyze-decision/prompt';

const root = join(__dirname, '..', '..');
const HEADER = '// GENERATED by scripts/sync-edge-schema.mjs from src/domain — do not edit.\n';

describe('edge function stays in sync with the app', () => {
  it.each(['schema.ts', 'parse.ts'])('%s matches src/domain (run npm run sync:edge)', (file) => {
    const source = readFileSync(join(root, 'src/domain', file), 'utf8').replace(/from '\.\/schema'/g, "from './schema.ts'");
    const edge = readFileSync(join(root, 'supabase/functions/analyze-decision', file), 'utf8');
    expect(edge).toBe(HEADER + source);
  });

  it('asks the model for exactly the fields the app validates', () => {
    const top = OUTPUT_SCHEMA as unknown as { required: string[]; properties: { scenarios: { items: { required: string[] } } } };
    expect([...top.required].sort()).toEqual(Object.keys(DecisionAnalysisSchema.shape).sort());
    expect([...top.properties.scenarios.items.required].sort()).toEqual(Object.keys(ScenarioSchema.shape).sort());
  });
});

describe('edge request validation', () => {
  it('rejects empty or tiny descriptions', () => {
    expect(validateRequest({ description: 'hi' }).ok).toBe(false);
    expect(validateRequest(null).ok).toBe(false);
    expect(validateRequest('text').ok).toBe(false);
  });

  it('rejects overly long descriptions', () => {
    expect(validateRequest({ description: 'x'.repeat(2001) }).ok).toBe(false);
  });

  it('trims optional fields and defaults depth to standard', () => {
    const result = validateRequest({ description: '  Should I move cities?  ', budget: '   ', priorities: 'Family', depth: 'extreme' });
    expect(result).toEqual({
      ok: true,
      value: { description: 'Should I move cities?', priorities: 'Family', budget: undefined, timeHorizon: undefined, depth: 'standard' },
    });
  });

  it('builds a prompt that reflects the requested depth', () => {
    const deep = buildUserPrompt({ description: 'Take the job?', depth: 'deep' });
    const standard = buildUserPrompt({ description: 'Take the job?', depth: 'standard' });
    expect(deep).toContain('3 or 4 paths');
    expect(standard).toContain('2 or 3 paths');
    expect(standard).toContain('"branches" to null');
  });
});
